name: backend-build

on:
  pull_request:
    branches: [main]
    paths:
      - "app/**"
      
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: unit-test
        run: cd app && docker-compose -f docker-compose.tests.yml run -e NODE_OPTIONS=--unhandled-rejections=warn node npm run test:unit
      - name: upload test coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report-${{ github.event.pull_request.number }}
          path: app/coverage/lcov-report
      
      - name: Add Table to PR Comment
        uses: actions/create-or-update-comment@v1
        with:
          body: |
            | Test Case | Result |
            |-----------|--------|
            | Test 1    | Passed |
            | Test 2    | Failed |
